# Generated by Django 5.2.14 on 2026-05-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_spinimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinimage',
            name='name',
            field=models.CharField(default='이름 없는 팽이', max_length=30),
        ),
    ]
