# Generated by Django 5.2.14 on 2026-05-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_spinimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinimage',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
