# Generated by Django 5.2.14 on 2026-05-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_spinimage_name_no_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinimage',
            name='battle_score',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='spinimage',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spinimage',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
