# Generated by Django 5.2.14 on 2026-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_spinimage_battle_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinimage',
            name='spin_type',
            field=models.CharField(choices=[('fire', '불꽃'), ('water', '물'), ('grass', '풀'), ('electric', '전기'), ('ice', '얼음'), ('steel', '강철'), ('dragon', '드래곤'), ('dark', '악'), ('psychic', '에스퍼'), ('fighting', '격투')], default='steel', editable=False, max_length=10),
        ),
    ]
