# Generated by Django 5.2.14 on 2026-06-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_spinimage_spin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinimage',
            name='spin_type',
            field=models.CharField(choices=[('fire', '불꽃'), ('water', '물'), ('grass', '풀'), ('electric', '전기'), ('ice', '얼음'), ('steel', '강철'), ('dragon', '드래곤'), ('dark', '악'), ('psychic', '에스퍼'), ('fighting', '격투')], default='', editable=False, max_length=10),
        ),
    ]
