# Generated by Django 5.2.14 on 2026-06-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_spinimage_spin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
